version: '3.7'

services:
  osm-data:
    container_name: osm-data
    build: ./osm-data
    environment:
      - DOWNLOAD_PBF=http://download.geofabrik.de/russia/siberian-fed-district-latest.osm.pbf
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
    command: "import"
  osm-routes:
    container_name: osm-routes
    restart: always
    build: ./osmr-backend
    ports:
    - "5000:5000"
    command: "run"
    volumes:
      - osm-file-data:/data
  osm-routes-import:
    container_name: osm-routes
    build: ./osmr-backend
    command: "import"
    volumes:
      - osm-file-data:/data
  osm-geocoder-import:
    container_name: osm-geocoder-import
    build: ./geocoder
    command: "import"
    volumes:
      - osm-file-data:/data
      - osm-postgres-data:/postgresdata
  osm-geocoder:
    container_name: osm-geocoder
    restart: always
    build: ./geocoder
    ports:
      - "7070:8080"
      - "6432:5432"
    command: "run"
    environment:
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
      - osm-postgres-data:/var/lib/postgresql/11/main

volumes:
  osm-file-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/osm/data
  osm-postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/osm/postgresdata
