version: '3.7'

services:
  osm-data:
    container_name: osm-data
    build: ./osm-data
    environment:
      - DOWNLOAD_PBF=http://download.geofabrik.de/russia/siberian-fed-district-latest.osm.pbf
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
    command: "import"
  osm-routes:
    container_name: osm-routes
    restart: always
    build: ./osmr-backend
    ports:
    - "7171:5000"
    command: "run"
    volumes:
      - osm-file-data:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  osm-routes-import:
    container_name: osm-routes-import
    build: ./osmr-backend
    command: "import"
    volumes:
      - osm-file-data:/data
  osm-geocoder-import:
    container_name: osm-geocoder-import
    build: ./geocoder
    command: "import"
    volumes:
      - osm-file-data:/data
      - osm-postgres-data:/postgresdata
  osm-geocoder:
    container_name: osm-geocoder
    restart: always
    build: ./geocoder
    ports:
      - "7070:8080"
      - "6432:5432"
    command: "run"
    environment:
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
      - osm-postgres-data:/var/lib/postgresql/12/main
      - ./local.php:/app/src/build/settings/local.php
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  osm-photon-import:
    container_name: osm-photon-import
    build: ./osm-photon
    volumes:
      - osm-photon-data:/data
    links:
      - "osm-geocoder:geocoder"
    command: "-host geocoder -port 5432 -nominatim-import -languages ru"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  osm-photon:
    container_name: osm-photon
    restart: always
    build: ./osm-photon
    ports:
      - "2322:2322"
    volumes:
      - osm-photon-data:/data
    links:
      - "osm-geocoder:geocoder"
    command: "-host geocoder -port 5432"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  osm-file-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/osm/data
  osm-postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/osm/data/postgresdata
  osm-photon-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/osm/photon
