version: '3.3'

services:
  osm-data:
    container_name: osm-data
    build: ./osm-data
    environment:
      - DOWNLOAD_PBF=http://download.geofabrik.de/russia/siberian-fed-district-latest.osm.pbf
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
    command: "import"
  osm-routes:
    container_name: osm-routes
    restart: always
    build: ./osmr-backend
    ports:
    - "5000:5000"
    command: "run"
    volumes:
      - osm-file-data:/data
  osm-routes-import:
    container_name: osm-routes
    build: ./osmr-backend
    depends_on:
      - osm-data
    command: "import"
    volumes:
      - osm-file-data:/data
  osm-geocoder:
    container_name: osm-geocoder
    restart: always
    build: ./geocoder
    ports:
      - "7070:8080"
    command: "run"
    environment:
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
      - osm-geocoder-data:/var/lib/postgresql/11/main
  osm-geocoder-init:
    container_name: osm-geocoder
    build: ./geocoder
    depends_on:
      - osm-data
    command: "import"
    environment:
      - DOWNLOAD_PBF_UPDATES=http://download.geofabrik.de/russia/siberian-fed-district-updates
    volumes:
      - osm-file-data:/data
      - osm-geocoder-data:/var/lib/postgresql/11/main


volumes:
  osm-file-data:
  osm-geocoder-data:
